### ISSUE TITLE
Handle the exception and restart the bot.

### ISSUE THREAD

**Issue by mdmccoy** [mdmccoy/420bot#4]
```
#<Thread:0x0000000002c16fb8@/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:22 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to slack.com:443 (Device or resource busy - getaddrinfo) (Errno::EBUSY)
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response/logger.rb:26:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:25:in `request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:10:in `post'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/api/endpoints/rtm.rb:41:in `rtm_start'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:125:in `restart_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:113:in `rescue in run_ping!'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:106:in `run_ping!'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:25:in `block (2 levels) in start_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/timer.rb:104:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:49:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:90:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:100:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:85:in `wait'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/async-1.17.0/lib/async/reactor.rb:157:in `run'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:28:in `block in start_async'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:109:in `run_ping!': Slack::RealTime::Client::ClientNotStartedError (Slack::RealTime::Client::ClientNotStartedError)
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:25:in `block (2 levels) in start_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/timer.rb:104:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:49:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:90:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:100:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:85:in `wait'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/async-1.17.0/lib/async/reactor.rb:157:in `run'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:28:in `block in start_async'
E, [2019-04-28T12:19:40.003540 #7904] ERROR -- : Failed to open TCP connection to slack.com:443 (Device or resource busy - getaddrinfo)
E, [2019-04-28T12:19:40.003583 #7904] ERROR -- : /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:945:in `connect'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:919:in `start'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response/logger.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:25:in `request'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:10:in `post'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/api/endpoints/rtm.rb:41:in `rtm_start'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:125:in `restart_async'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:113:in `rescue in run_ping!'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:106:in `run_ping!'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:25:in `block (2 levels) in start_async'
/usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/timer.rb:104:in `fire'
/usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:49:in `fire'
/usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:90:in `fire'
/usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:100:in `fire'
/usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:85:in `wait'
/usr/local/rvm/gems/ruby-2.6.0/gems/async-1.17.0/lib/async/reactor.rb:157:in `run'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:28:in `block in start_async'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to slack.com:443 (Device or resource busy - getaddrinfo) (Errno::EBUSY)
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response/logger.rb:26:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:25:in `request'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/faraday/request.rb:10:in `post'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/web/api/endpoints/rtm.rb:41:in `rtm_start'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:125:in `restart_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:113:in `rescue in run_ping!'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:106:in `run_ping!'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:25:in `block (2 levels) in start_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/timer.rb:104:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:49:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:90:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:100:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:85:in `wait'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/async-1.17.0/lib/async/reactor.rb:157:in `run'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:28:in `block in start_async'
/usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/client.rb:109:in `run_ping!': Slack::RealTime::Client::ClientNotStartedError (Slack::RealTime::Client::ClientNotStartedError)
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:25:in `block (2 levels) in start_async'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/timer.rb:104:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:49:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/events.rb:90:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:100:in `fire'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/timers-4.3.0/lib/timers/group.rb:85:in `wait'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/async-1.17.0/lib/async/reactor.rb:157:in `run'
	from /usr/local/rvm/gems/ruby-2.6.0/gems/slack-ruby-client-0.14.1/lib/slack/real_time/concurrency/async.rb:28:in `block in start_async'
```

Here's an excerpt from the logs when this happens. Lets work on a way to handle this, and then restart the bot when it occurs.

**Comment by mdmccoy** [comment]
First attempt in https://github.com/mdmccoy/420bot/pull/6

**Comment by mdmccoy** [comment]
That first attempt does not appear to have worked. Will need to investigate more.

**Comment by mdmccoy** [comment]
Lets try just rescuing StandardError instead, and see if that works at restarting the bot.

**Comment by mdmccoy** [comment]
2nd try on https://github.com/mdmccoy/420bot/pull/8
